### ISSUE TITLE
pilas-tutoriales: tutorial de nave error al disparar enemigo

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/pilas-tutoriales#3]
Reportado por Fernando Toledo:

En el tutorial de la nave cuando defino los enemigos y con la nave le disparo a uno pasa el siguiente error:

```
Uncaught node.js Error 

TypeError: Cannot read property 'actualizar_comportamientos' of undefined
    at Normal.actualizar (file:///usr/share/pilas-tutoriales/src/pilasweb.js:1603:28)
    at GestorDeEscenas.actualizar (file:///usr/share/pilas-tutoriales/src/pilasweb.js:2012:16)
    at Mundo.actualizar (file:///usr/share/pilas-tutoriales/src/pilasweb.js:2557:29)
    at Pilas.actualizar (file:///usr/share/pilas-tutoriales/src/pilasweb.js:2787:20)
    at my_tick (file:///usr/share/pilas-tutoriales/src/pilasweb.js:2777:18)
    at Function.b.dispatchEvent (file:///usr/share/pilas-tutoriales/src/easeljs-0.6.1.min.js:14:483)
    at Function.c._tick (file:///usr/share/pilas-tutoriales/src/easeljs-0.6.1.min.js:20:334)
    at c._handleTimeout (file:///usr/share/pilas-tutoriales/src/easeljs-0.6.1.min.js:19:195)

```

**Comment by hugoruscitti** [comment]
Cerrado con el commit: https://github.com/hugoruscitti/pilas-tutoriales/commit/631632f4305b4bec92654d689bb3d411845eaa32
